name: DevOps CI/CD Lab

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Do the lab stuff
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Lint
      uses: github/super-linter@v4.9.7
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        username: sosnoviybor
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest, ${{ github.run_number }}
