name: DevOps CI/CD Lab

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Do the lab stuff
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Lint
      uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v1
    - name: Build Docker image and push it
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }} " | docker login -u "sosnoviybor" --password-stdin
        docker image build -t devops-lab4 .
        docker push devops-lab4
